# Autogenerated file from gulp task

# App = require("./demo/application.coffee")

# onDeviceReady = ->
#   App.start()
#
#
# $(document).ready onDeviceReady
#
# document.addEventListener 'deviceready', onDeviceReady, false
#
# module.exports = App
